[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "weather-cli"
description = "A weather CLI"
requires-python = ">=3.8"
version = "0.1.0"
license = { text = "MIT" }

[project.scripts]
weather = "weather_cli.weather:main"
